// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "@hotwired/stimulus"
import NestedForm from 'stimulus-rails-nested-form'

import HelloController from "./hello_controller"
application.register("hello", HelloController)

const application = Application.start()
application.register('nested-form', NestedForm)
