# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

currency = Currency.create(currency_name: "COP", description: "Pesos colombianos")
currency = Currency.create(currency_name: "USD", description: "Dólar estadounidense")
category = Category.create(category_name:"Alimentación", description: "Mercado")
category = Category.create(category_name:"Alimentación", description: "Restaurantes- cafeterías")
category = Category.create(category_name:"Alimentación", description: "Domicilios")
category = Category.create(category_name:"Vivienda", description: "Arrendamiento-cuota de crédito hipotecario")
category = Category.create(category_name:"Vivienda", description: "Administración")
category = Category.create(category_name:"Vivienda", description: "Acueducto, alcantarillado y aseo")
category = Category.create(category_name:"Vivienda", description: "Energía eléctrica")
category = Category.create(category_name:"Vivienda", description: "Gas")
category = Category.create(category_name:"Vivienda", description: "Teléfono-TV básica-Internet")
category = Category.create(category_name:"Vivienda", description: "Otros servicios de internet")
category = Category.create(category_name:"Vivienda", description: "Muebles, aparatos y utensilios de hogar")
category = Category.create(category_name:"Vivienda", description: "Repuestos o reparaciones")
category = Category.create(category_name:"Vivienda", description: "Artículos de aseo del hogar")
category = Category.create(category_name:"Vivienda", description: "Servicio doméstico")
category = Category.create(category_name:"Vivienda", description: "Impuesto predial")
category = Category.create(category_name:"Vivienda", description: "Valorización")
category = Category.create(category_name:"Transporte", description: "Buses")
category = Category.create(category_name:"Transporte", description: "Taxi-Uber-Cabify y similares")
category = Category.create(category_name:"Transporte", description: "Bicitaxi y otros medios de transporte urbano")
category = Category.create(category_name:"Transporte", description: "Gasolina")
category = Category.create(category_name:"Transporte", description: "Parqueaderos")
category = Category.create(category_name:"Transporte", description: "Lavado de vehículo")
category = Category.create(category_name:"Transporte", description: "Cambios de aceite, llantas y servicios de mecánica")
category = Category.create(category_name:"Transporte", description: "Peajes y otros gastos de vehículo")
category = Category.create(category_name:"Transporte", description: "Impuesto de vehículos")
category = Category.create(category_name:"Transporte", description: "SOAT y otros seguros de vehículos")
category = Category.create(category_name:"Transporte", description: "Transporte intermunicipal y transporte aéreo")
category = Category.create(category_name:"Salud", description: "Gastos de aseguramiento del sistema obligatorio")
category = Category.create(category_name:"Salud", description: "Medicina prepagada, seguros de salud y similares")
category = Category.create(category_name:"Salud", description: "Consultas médicas, exámenes y tratamientos")
category = Category.create(category_name:"Salud", description: "Medicinas y anticonceptivos")
category = Category.create(category_name:"Salud", description: "Peluquería")
category = Category.create(category_name:"Salud", description: "Cosméticos y tratamientos de belleza")
category = Category.create(category_name:"Salud", description: "Gimnasio y actividades deportivas")
category = Category.create(category_name:"Entretenimiento", description: "Libros y revistas")
category = Category.create(category_name:"Entretenimiento", description: "Cine, música y películas")
category = Category.create(category_name:"Entretenimiento", description: "Rumba")
category = Category.create(category_name:"Entretenimiento", description: "Conciertos, teatro y espectáculos")
category = Category.create(category_name:"Entretenimiento", description: "Artículos y servicios para aficiones")
category = Category.create(category_name:"Entretenimiento", description: "Tecnología y gadgets")
category = Category.create(category_name:"Entretenimiento", description: "Mascotas (alimentación, veterinaria y accesorios)")
category = Category.create(category_name:"Entretenimiento", description: "Turismo")
category = Category.create(category_name:"Vestuario", description: "Ropa")
category = Category.create(category_name:"Vestuario", description: "Zapatos")
category = Category.create(category_name:"Vestuario", description: "Uniformes")
category = Category.create(category_name:"Vestuario", description: "Joyería y accesorios")
category = Category.create(category_name:"Vestuario", description: "Lavandería")
category = Category.create(category_name:"Vestuario", description: "Modistería y zapatería")
category = Category.create(category_name:"Educación", description: "Matrículas y pensiones")
category = Category.create(category_name:"Educación", description: "Cursos libres y seminarios")
category = Category.create(category_name:"Educación", description: "Otras suscripciones")
category = Category.create(category_name:"Educación", description: "Libros y artículos escolares")
category = Category.create(category_name:"Educación", description: "Coaching / Mentoring")
category = Category.create(category_name:"Comunicación", description: "Celular")
category = Category.create(category_name:"Comunicación", description: "Minutos e internet (calle)")
category = Category.create(category_name:"Comunicación", description: "Papelería")
category = Category.create(category_name:"Comunicación", description: "Servicios de correo")
category = Category.create(category_name:"Empresa", description: "Gastos notariales y otros gastos legales")
category = Category.create(category_name:"Empresa", description: "Servicios contables")
category = Category.create(category_name:"Empresa", description: "Salarios-contratos")
category = Category.create(category_name:"Otros", description: "Cigarrillos y bebidas alcohólicas")
category = Category.create(category_name:"Otros", description: "Donaciones")
category = Category.create(category_name:"Otros", description: "Regalos")
category = Category.create(category_name:"Otros", description: "Mesadas")
category = Category.create(category_name:"Otros", description: "Seguros de vida")
category = Category.create(category_name:"Otros", description: "Seguros de hogar")
category = Category.create(category_name:"Otros", description: "Otros seguros")
category = Category.create(category_name:"Otros", description: "Ayuda a familiares")